import Head from 'next/head'
import Banner from '../components/Banner'
import ChatBot from '../components/ChatBot'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Puntos Texaco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner></Banner>

      <main>
        <ChatBot></ChatBot>
      </main>

      <Footer></Footer>
    </div>
  )
}
